# Continuous integration for Windows.
# Based on https://github.com/astropy/ci-helpers

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-tools\\appveyor\\windows_sdk.cmd"
      TEST_CMD: "nosetests -v --with-doctests fatiando test"

  matrix:
      - PYTHON_ARCH: "64"
        PYTHON_VERSION: "2.7"
      - PYTHON_ARCH: "32"
        PYTHON_VERSION: "2.7"

platform:
    -x64

install:
    # Install Miniconda
    - "powershell ci-tools/appveyor/install-miniconda.ps1"
    # Set path again, need to find a way to avoid doing this again
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    # Test that PATH is set correctly
    - "conda --version"
    - "python --version"
    # Install dependencies
    - "%CMD_IN_ENV% conda install --yes --file requirements.txt"
    - "%CMD_IN_ENV% conda install --yes --file test\\requirements-conda.txt"
    - "%CMD_IN_ENV% pip install -r test\\requirements-pip.txt"
    # Build and install the Fatiando package
    - "%CMD_IN_ENV% python setup.py sdist --formats=zip"
    - ps: "ls dist"
    - "%CMD_IN_ENV% pip install --pre --find-links dist/ fatiando"
    - "%CMD_IN_ENV% python -c 'import fatiando; print(fatiando.__version__)'"

test_script:
    - "%CMD_IN_ENV% %TEST_CMD%"

# Not a .NET project, we build ci-helpers in the install step instead
build: false
